version: '3.9'

services:
  server:
    container_name: game-server
    image: quangcoder/delivery-game:servergame # Nó sẽ pull từ đây
    # Đã bỏ phần build để tránh lỗi thiếu file code trên VPS
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "54777:54777/udp"
      - "54555:54555"
    networks:
      - game-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://game-sql:1433;databaseName=future-city;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=quang532006@

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: game-db-init
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - game-network
    entrypoint: >
      /opt/mssql-tools18/bin/sqlcmd -S game-sql -U sa -P "quang532006@" -C  -Q "IF DB_ID('future-city') IS NULL CREATE DATABASE [future-city]"

  sql-server:
    container_name: game-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "quang532006@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    networks:
      - game-network
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "quang532006@", "-C", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  game-network:
    driver: bridge
    name: game-network
